public class Kweakte row Java{
    public static void main(String[]args){
        int arr[][]={};
        int n=arr.length;
        int pairs[][]={
            {2,0},
            {4,1},
            {1,2}.
            {2,3},
            {5,3}.

        };
        arrays.sort(pairs,(a.b))->{
            if(a[]=b[0]) return a[1]-b[1];
            else return a[0]-b[0];

        }

}



pubic class PascalTraning{
    public list<list<integer>>generate(int numrow){
        list<list<list<integer>>result =new arrays List<List<list<integer>>();
        result.add(new Arraylist<>();)
        result.get(0),add(1);
        
        for (int i=1;i<numrow;i++){<>
            list<integer> row=new Arraylist();
            list<integer>prevrow=result.get(i-1);
            

        }

    }
}